name: reactivity_benchmark
description: Benchmark comparing different standalone Dart reactivity/signals frameworks.
repository: https://github.com/medz/dart-reactivity-benchmark
funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

version: 0.0.1
environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.1.1
