name: reactivity_benchmark
description: Benchmark comparing different standalone Dart reactivity/signals frameworks.
repository: https://github.com/medz/dart-reactivity-benchmark
funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

version: 0.0.1
environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  alien_signals: ^0.0.10
  solidart: ^1.5.4
  signals_core: ^6.0.2
  preact_signals: ^1.8.3
  state_beacon_core: ^1.0.0
  mobx: ^2.5.0
